# Generated by Django 5.0 on 2025-11-16 21:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Predio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('superficie', models.DecimalField(decimal_places=2, max_digits=10)),
                ('zona', models.CharField(choices=[('Puerto Montt', 'Puerto Montt'), ('Osorno', 'Osorno'), ('Río Bueno', 'Río Bueno')], max_length=50)),
                ('tipo_suelo', models.CharField(choices=[('Andisol', 'Andisol'), ('Ultisol', 'Ultisol'), ('Alfisol', 'Alfisol')], max_length=50)),
                ('cultivo_actual', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predios', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'predios',
                'ordering': ['zona', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Medicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('ph', models.DecimalField(decimal_places=2, max_digits=4)),
                ('temperatura', models.DecimalField(decimal_places=2, max_digits=5)),
                ('humedad', models.DecimalField(decimal_places=2, max_digits=5)),
                ('nitrogeno', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fosforo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('potasio', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('origen', models.CharField(choices=[('wemos', 'Sensor Wemos'), ('manual', 'Ingreso Manual')], default='manual', max_length=20)),
                ('predio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mediciones', to='api.predio')),
            ],
            options={
                'db_table': 'mediciones',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Recomendacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semana_inicio', models.DateField(blank=True, null=True)),
                ('fecha_calculo', models.DateTimeField(auto_now_add=True)),
                ('ph_promedio', models.DecimalField(decimal_places=2, max_digits=4, null=True)),
                ('temp_promedio', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('humedad_promedio', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('n_promedio', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('p_promedio', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('k_promedio', models.DecimalField(decimal_places=4, max_digits=10, null=True)),
                ('urea_kg_ha', models.DecimalField(decimal_places=2, max_digits=10)),
                ('superfosfato_kg_ha', models.DecimalField(decimal_places=2, max_digits=10)),
                ('muriato_potasio_kg_ha', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cal_kg_ha', models.DecimalField(decimal_places=2, max_digits=10)),
                ('urea_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('superfosfato_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('muriato_potasio_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cal_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('factor_zona', models.DecimalField(decimal_places=2, max_digits=4)),
                ('factor_suelo', models.DecimalField(decimal_places=2, max_digits=4)),
                ('factor_precipitacion', models.DecimalField(decimal_places=2, max_digits=4)),
                ('medicion', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recomendacion', to='api.medicion')),
                ('predio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recomendaciones', to='api.predio')),
            ],
            options={
                'db_table': 'recomendaciones',
                'ordering': ['-fecha_calculo'],
            },
        ),
        migrations.AddIndex(
            model_name='medicion',
            index=models.Index(fields=['predio', '-fecha'], name='mediciones_predio__fc1416_idx'),
        ),
    ]
