# Generated by Django 5.0 on 2025-11-20 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predio',
            name='cultivo_actual',
            field=models.CharField(blank=True, choices=[('Papa temprana', 'Papa temprana'), ('Avena forrajera', 'Avena forrajera'), ('Ballica perenne', 'Ballica perenne')], max_length=100, null=True),
        ),
    ]
